LabeledAsserts.dfy(63,9): Warning: Argument to 'old' does not dereference the mutable heap, so this use of 'old' has no effect
LabeledAsserts.dfy(63,30): Warning: Argument to 'old' does not dereference the mutable heap, so this use of 'old' has no effect
LabeledAsserts.dfy(16,2): Error: assertion might not hold
LabeledAsserts.dfy(42,2): Error: assertion might not hold
LabeledAsserts.dfy(43,2): Error: assertion might not hold
LabeledAsserts.dfy(91,4): Error: assertion might not hold
LabeledAsserts.dfy(105,4): Error: assertion might not hold
LabeledAsserts.dfy(107,4): Error: assertion might not hold
LabeledAsserts.dfy(128,4): Error: assertion might not hold
LabeledAsserts.dfy(142,6): Error: assertion might not hold
LabeledAsserts.dfy(146,6): Error: assertion might not hold
LabeledAsserts.dfy(206,4): Error: assertion might not hold
LabeledAsserts.dfy(207,4): Error: assertion might not hold
LabeledAsserts.dfy(211,4): Error: assertion might not hold
LabeledAsserts.dfy(224,4): Error: assertion might not hold
LabeledAsserts.dfy(226,4): Error: assertion might not hold
LabeledAsserts.dfy(232,4): Error: assertion might not hold
LabeledAsserts.dfy(252,6): Error: the calculation step between the previous line and this line could not be proved
LabeledAsserts.dfy(265,2): Error: assertion might not hold
LabeledAsserts.dfy(25,2): Error: assertion might not hold
LabeledAsserts.dfy(27,2): Error: assertion might not hold
LabeledAsserts.dfy(28,2): Error: assertion might not hold
LabeledAsserts.dfy(29,2): Error: assertion might not hold
LabeledAsserts.dfy(32,2): Error: assertion might not hold
LabeledAsserts.dfy(162,2): Error: assertion might not hold
LabeledAsserts.dfy(172,4): Error: assertion might not hold
LabeledAsserts.dfy(189,6): Error: assertion might not hold
LabeledAsserts.dfy(193,6): Error: assertion might not hold

Dafny program verifier finished with 11 verified, 26 errors
