SubsetTypes.dfy(7,18): Error: value does not satisfy the subset constraints of 'nat'
SubsetTypes.dfy(8,9): Error: value does not satisfy the subset constraints of 'nat'
SubsetTypes.dfy(10,23): Error: value does not satisfy the subset constraints of 'nat'
SubsetTypes.dfy(11,9): Error: cannot establish the existence of LHS values that satisfy the such-that predicate. Note, no trigger was found for the such-that predicate, which may be the reason the proof failed. To give a trigger explicitly, use the {:trigger} attribute. For more information, see the section on quantifier instantiation rules in the reference manual.
SubsetTypes.dfy(15,15): Error: cannot establish the existence of LHS values that satisfy the such-that predicate. Note, no trigger was found for the such-that predicate, which may be the reason the proof failed. To give a trigger explicitly, use the {:trigger} attribute. For more information, see the section on quantifier instantiation rules in the reference manual.
SubsetTypes.dfy(16,6): Error: cannot establish the existence of LHS values that satisfy the such-that predicate. Note, no trigger was found for the such-that predicate, which may be the reason the proof failed. To give a trigger explicitly, use the {:trigger} attribute. For more information, see the section on quantifier instantiation rules in the reference manual.
SubsetTypes.dfy(19,11): Error: value does not satisfy the subset constraints of 'nat'
SubsetTypes.dfy(21,15): Error: value does not satisfy the subset constraints of 'nat'
SubsetTypes.dfy(23,8): Error: value does not satisfy the subset constraints of 'nat'
SubsetTypes.dfy(31,6): Error: value does not satisfy the subset constraints of 'nat'
SubsetTypes.dfy(31,7): Error: value does not satisfy the subset constraints of 'nat'
SubsetTypes.dfy(42,24): Error: value does not satisfy the subset constraints of 'nat'
SubsetTypes.dfy(44,15): Error: value does not satisfy the subset constraints of 'nat'
SubsetTypes.dfy(49,15): Error: value does not satisfy the subset constraints of 'nat'
SubsetTypes.dfy(51,9): Error: value does not satisfy the subset constraints of 'int -> nat' (possible cause: it may be partial or have read effects)
SubsetTypes.dfy(56,4): Error: value does not satisfy the subset constraints of 'nat'
SubsetTypes.dfy(63,23): Error: value of expression (of type 'set<int>') is not known to be an instance of type 'set<nat>'
SubsetTypes.dfy(64,9): Error: value of expression (of type 'set<int>') is not known to be an instance of type 'set<nat>'
SubsetTypes.dfy(66,28): Error: value of expression (of type 'set<int>') is not known to be an instance of type 'set<nat>'
SubsetTypes.dfy(67,9): Error: cannot establish the existence of LHS values that satisfy the such-that predicate. Note, no trigger was found for the such-that predicate, which may be the reason the proof failed. To give a trigger explicitly, use the {:trigger} attribute. For more information, see the section on quantifier instantiation rules in the reference manual.
SubsetTypes.dfy(71,20): Error: cannot establish the existence of LHS values that satisfy the such-that predicate. Note, no trigger was found for the such-that predicate, which may be the reason the proof failed. To give a trigger explicitly, use the {:trigger} attribute. For more information, see the section on quantifier instantiation rules in the reference manual.
SubsetTypes.dfy(72,6): Error: cannot establish the existence of LHS values that satisfy the such-that predicate. Note, no trigger was found for the such-that predicate, which may be the reason the proof failed. To give a trigger explicitly, use the {:trigger} attribute. For more information, see the section on quantifier instantiation rules in the reference manual.
SubsetTypes.dfy(75,11): Error: value of expression (of type 'set<int>') is not known to be an instance of type 'set<nat>'
SubsetTypes.dfy(77,15): Error: value of expression (of type 'set<int>') is not known to be an instance of type 'set<nat>'
SubsetTypes.dfy(79,8): Error: value of expression (of type 'set<int>') is not known to be an instance of type 'set<nat>'
SubsetTypes.dfy(87,6): Error: value of expression (of type 'set<int>') is not known to be an instance of type 'set<nat>'
SubsetTypes.dfy(87,7): Error: value of expression (of type 'set<int>') is not known to be an instance of type 'set<nat>'
SubsetTypes.dfy(98,24): Error: value of expression (of type 'set<int>') is not known to be an instance of type 'set<nat>'
SubsetTypes.dfy(100,15): Error: value of expression (of type 'set<int>') is not known to be an instance of type 'set<nat>'
SubsetTypes.dfy(101,9): Error: value of expression (of type 'set<int> -> set<int>') is not known to be an instance of type 'set<int> ~> set<nat>'
SubsetTypes.dfy(106,15): Error: value of expression (of type 'set<int>') is not known to be an instance of type 'set<nat>'
SubsetTypes.dfy(108,9): Error: value does not satisfy the subset constraints of 'set<int> -> set<nat>' (possible cause: it may be partial or have read effects)
SubsetTypes.dfy(113,4): Error: value of expression (of type 'set<int>') is not known to be an instance of type 'set<nat>'
SubsetTypes.dfy(123,32): Error: value does not satisfy the subset constraints of 'nat'
SubsetTypes.dfy(125,20): Error: value does not satisfy the subset constraints of 'nat'
SubsetTypes.dfy(135,25): Error: value of expression (of type 'nat ~> int') is not known to be an instance of type 'int ~> int'
SubsetTypes.dfy(136,25): Error: value of expression (of type 'nat ~> nat') is not known to be an instance of type 'int ~> int'
SubsetTypes.dfy(141,25): Error: value of expression (of type 'int ~> int') is not known to be an instance of type 'int ~> nat'
SubsetTypes.dfy(143,25): Error: value of expression (of type 'nat ~> int') is not known to be an instance of type 'int ~> nat'
SubsetTypes.dfy(144,25): Error: value of expression (of type 'nat ~> nat') is not known to be an instance of type 'int ~> nat'
SubsetTypes.dfy(157,25): Error: value of expression (of type 'int ~> int') is not known to be an instance of type 'nat ~> nat'
SubsetTypes.dfy(159,25): Error: value of expression (of type 'nat ~> int') is not known to be an instance of type 'nat ~> nat'
SubsetTypes.dfy(169,20): Error: cannot establish the existence of LHS values that satisfy the such-that predicate. Note, no trigger was found for the such-that predicate, which may be the reason the proof failed. To give a trigger explicitly, use the {:trigger} attribute. For more information, see the section on quantifier instantiation rules in the reference manual.
SubsetTypes.dfy(182,11): Error: value of expression (of type 'int -> int') is not known to be an instance of type 'int ~> nat'
SubsetTypes.dfy(199,25): Error: value of expression (of type 'Person?') is not known to be an instance of type 'Person', because it might be null
SubsetTypes.dfy(204,23): Error: value of expression (of type 'Person?') is not known to be an instance of type 'Person', because it might be null
SubsetTypes.dfy(213,11): Error: value of expression (of type 'array<Person>') is not known to be an instance of type 'array<Person?>'
SubsetTypes.dfy(216,11): Error: value of expression (of type 'array<Person?>') is not known to be an instance of type 'array<Person>'
SubsetTypes.dfy(232,11): Error: value of expression (of type 'seq<Person?>') is not known to be an instance of type 'seq<Person>'
SubsetTypes.dfy(241,11): Error: value of expression (of type 'seq<Person?>') is not known to be an instance of type 'seq<Person>'
SubsetTypes.dfy(270,28): Error: value does not satisfy the subset constraints of 'byte'
SubsetTypes.dfy(271,30): Error: value does not satisfy the subset constraints of 'byte'
SubsetTypes.dfy(272,30): Error: value does not satisfy the subset constraints of 'byte'
SubsetTypes.dfy(273,38): Error: value does not satisfy the subset constraints of 'byte'
SubsetTypes.dfy(278,33): Error: value does not satisfy the subset constraints of 'byte'
SubsetTypes.dfy(279,39): Error: value does not satisfy the subset constraints of 'byte'
SubsetTypes.dfy(284,28): Error: value does not satisfy the subset constraints of 'byte'
SubsetTypes.dfy(285,29): Error: value of expression (of type 'seq<int>') is not known to be an instance of type 'seq<byte>'
SubsetTypes.dfy(286,29): Error: value of expression (of type 'set<int>') is not known to be an instance of type 'set<byte>'
SubsetTypes.dfy(287,29): Error: value of expression (of type 'multiset<int>') is not known to be an instance of type 'multiset<byte>'
SubsetTypes.dfy(288,29): Error: value of expression (of type 'map<int, int>') is not known to be an instance of type 'map<byte, byte>'
SubsetTypes.dfy(318,18): Error: value does not satisfy the subset constraints of 'nat'
SubsetTypes.dfy(323,20): Error: value does not satisfy the subset constraints of 'nat'
SubsetTypes.dfy(330,20): Error: result of operation might violate newtype constraint for 'Nat'
SubsetTypes.dfy(337,20): Error: result of operation might violate newtype constraint for 'Nat'
SubsetTypes.dfy(342,7): Error: cannot find witness that shows type is inhabited (only tried 0); try giving a hint through a 'witness' or 'ghost witness' clause, or use 'witness *' to treat as a possibly empty type
SubsetTypes.dfy(343,18): Error: value does not satisfy the subset constraints of 'Nat'
SubsetTypes.dfy(347,10): Error: cannot find witness that shows type is inhabited (only tried 0); try giving a hint through a 'witness' or 'ghost witness' clause, or use 'witness *' to treat as a possibly empty type
SubsetTypes.dfy(348,18): Error: result of operation might violate newtype constraint for 'Nat'
SubsetTypes.dfy(352,7): Error: cannot find witness that shows type is inhabited (only tried 0); try giving a hint through a 'witness' or 'ghost witness' clause, or use 'witness *' to treat as a possibly empty type
SubsetTypes.dfy(360,21): Error: possible division by zero
SubsetTypes.dfy(365,23): Error: possible division by zero
SubsetTypes.dfy(377,19): Error: value does not satisfy the subset constraints of 'X'
SubsetTypes.dfy(379,19): Error: value does not satisfy the subset constraints of 'Y'
SubsetTypes.dfy(381,19): Error: value does not satisfy the subset constraints of 'Y'
SubsetTypes.dfy(383,19): Error: value does not satisfy the subset constraints of 'Y'
SubsetTypes.dfy(385,19): Error: value of expression (of type 'C?') is not known to be an instance of type 'C', because it might be null
SubsetTypes.dfy(390,29): Error: value does not satisfy the subset constraints of 'int --> int' (possible cause: it may have read effects)
SubsetTypes.dfy(392,28): Error: value does not satisfy the subset constraints of 'int -> int' (possible cause: it may be partial or have read effects)
SubsetTypes.dfy(394,28): Error: value does not satisfy the subset constraints of 'int -> int' (possible cause: it may be partial or have read effects)
SubsetTypes.dfy(396,28): Error: value of expression (of type 'int ~> int') is not known to be an instance of type 'int ~> nat'
SubsetTypes.dfy(398,26): Error: value of expression (of type 'int ~> int') is not known to be an instance of type 'int ~> X'
SubsetTypes.dfy(401,9): Error: value does not satisfy the subset constraints of 'nat'
SubsetTypes.dfy(411,7): Error: cannot find witness that shows type is inhabited (only tried 'D'); try giving a hint through a 'witness' or 'ghost witness' clause, or use 'witness *' to treat as a possibly empty type
SubsetTypes.dfy(413,7): Error: cannot find witness that shows type is inhabited (only tried 'D'); try giving a hint through a 'witness' or 'ghost witness' clause, or use 'witness *' to treat as a possibly empty type
SubsetTypes.dfy(429,4): Error: assertion might not hold
SubsetTypes.dfy(436,6): Error: assertion might not hold
SubsetTypes.dfy(445,6): Error: assertion might not hold
SubsetTypes.dfy(452,6): Error: assertion might not hold
SubsetTypes.dfy(459,6): Error: assertion might not hold
SubsetTypes.dfy(464,4): Error: assertion might not hold

Dafny program verifier finished with 13 verified, 91 errors
Total resources used is 738600
Max resources used by VC is 76700
